/**
 * cookbook-resources.ts
 *
 * Single source of truth for the Jumpstart course chapter list and the
 * prompt-recipe list. Both Resources.tsx and searchIndex.ts import from here
 * so that any count displayed in search results or UI is always derived from
 * the real array length — never a hardcoded literal.
 */

// ─── Jumpstart Course Chapters ───────────────────────────────────────────────

export interface JumpstartChapter {
  title: string;
  subtitle: string;
  description: string;
  image: string;
  chapterId: string | null;
  lesson: string;
}

export const jumpstartChapters: JumpstartChapter[] = [
  { title: "The 5-Minute Mindset", subtitle: "Stop guessing, start targeting", description: "Change your entire approach to talking with AI. Vague prompt = vague answer. Specific prompt = useful answer.", image: "/chapters/ch1-Specificity_small.png", chapterId: "ch01",
    lesson: "The single biggest mistake people make with AI: they type vague requests and expect specific answers. \"Help me with this report\" gives you generic filler. \"Summarize the Q3 budget variance report in 3 bullet points for the County Administrator\" gets you something you can actually use.\n\nThe fix takes 5 minutes to learn: before you type anything, answer the 5W+H — Who needs this? What exactly do I need? When/where will it be used? Why does it matter? How should it look?\n\nCounty example: Instead of \"Write an email about the meeting,\" try \"Write a 3-paragraph email to department directors summarizing today's budget workshop. Include the three decisions that were made and the April 15 deadline for submitting revised numbers.\"" },
  { title: "Your First Magic Prompt", subtitle: "The RTCO formula", description: "The 4-step recipe every great prompt uses: Role, Task, Context, Output format. The master key to every prompt.", image: "/chapters/ch2-FiveWandoneH_small.png", chapterId: "ch02",
    lesson: "RTCO is the skeleton key. Every effective prompt has four parts:\n\n• Role — Tell the AI who it is. \"You are a county budget analyst\" sets the tone, vocabulary, and perspective.\n• Task — What do you need done? Be specific. \"Summarize\" is different from \"compare\" is different from \"draft.\"\n• Context — Background the AI needs. Paste the data, describe the audience, state constraints.\n• Output — How should the result look? \"Bullet list under 200 words\" or \"formal memo with headers.\"\n\nCounty example:\nRole: You are a public information officer for Manatee County.\nTask: Draft a press release announcing the new online permitting system.\nContext: Launches April 1. Covers building, zoning, and code enforcement permits. Replaces paper forms. Available at mymanatee.org.\nOutput: 250 words, AP style, include a quote placeholder for the County Administrator." },
  { title: "The Persona Pattern", subtitle: "Act as...", description: "Give the AI a uniform and a name tag. When you say 'act as,' the AI snaps into that character's knowledge and tone.", image: "/chapters/ch3-persona-pattern_small.png", chapterId: "ch03",
    lesson: "When you tell AI to \"act as\" a specific role, it shifts its entire vocabulary, reasoning style, and assumptions. \"Act as a building inspector\" produces different output than \"act as a communications director\" — even for the same topic.\n\nEffective personas include:\n• Job title and organization\n• Years of experience or expertise level\n• Specific knowledge domains\n• Communication style expectations\n\nCounty example: \"Act as a senior grants coordinator for Manatee County with 15 years of experience writing federal grant applications. You specialize in FEMA hazard mitigation grants and HUD community development block grants. Write in formal federal grant language.\"\n\nPro tip: Stack personas for peer review. Write something as one role, then critique it as another. \"Now act as the grant reviewer and identify the three weakest sections of this application.\"" },
  { title: "Show and Tell", subtitle: "Few-shot learning", description: "Don't tell the AI what you want — show it. One good example is worth ten instructions.", image: "/chapters/ch4-showand-tell_small.png", chapterId: "ch04",
    lesson: "Instead of describing the format you want, paste an example of it. AI learns patterns from examples faster than from instructions.\n\nZero-shot: \"Write a status update.\" (AI guesses the format)\nOne-shot: \"Here's an example status update: [example]. Now write one for my project.\"\nFew-shot: Give 2-3 examples, then ask for a new one. The AI will match the pattern.\n\nCounty example: Paste a well-formatted board memo you've written before, then say: \"Using this exact format and tone, write a new memo about [topic].\" The AI will match your headers, paragraph length, level of detail, and voice.\n\nThis works for any repeating format: inspection reports, meeting minutes, public notices, email templates. One good example saves you from writing a paragraph of formatting instructions." },
  { title: "Thinking Out Loud", subtitle: "Chain-of-thought", description: "If you want better answers, ask the AI to show its work. Step-by-step reasoning improves accuracy on complex tasks.", image: "/chapters/ch5-task_chaining_small.png", chapterId: "ch05",
    lesson: "For complex questions, ask the AI to reason step-by-step before giving a final answer. This reduces errors on math, logic, policy analysis, and multi-factor decisions.\n\nAdd one of these phrases:\n• \"Think through this step by step.\"\n• \"Show your reasoning before giving your answer.\"\n• \"Walk me through your analysis.\"\n\nCounty example: \"We need to decide whether to extend the contract with our current fleet maintenance vendor or go to bid. Think through this step by step, considering: current contract terms, market rates, transition costs, service quality history, and procurement timeline requirements under Florida Statute 287.\"\n\nWithout chain-of-thought, you get a surface-level recommendation. With it, you get a structured analysis you can actually bring to a meeting." },
  { title: "Taming the Output", subtitle: "Formatting", description: "Don't just ask for an answer — decide how it should look. Tables, bullets, memos, JSON.", image: "/chapters/ch6-Taming_the_Output_small.png", chapterId: "ch06",
    lesson: "AI will give you a wall of text unless you tell it otherwise. Specify the format and you get something usable immediately.\n\nFormats that work well:\n• \"Respond in a markdown table with columns: Item, Status, Owner, Due Date\"\n• \"Use bullet points, no more than 8 items\"\n• \"Format as a formal memo with these headers: Background, Analysis, Recommendation\"\n• \"Give me exactly 3 options, each in 2 sentences\"\n\nLength controls:\n• \"Keep it under 200 words\"\n• \"One paragraph only\"\n• \"Executive summary: 3 sentences max\"\n\nCounty example: \"Summarize these 14 public comments on the zoning amendment. Format as a table with columns: Commenter Name, Position (Support/Oppose/Neutral), Key Concern, Staff Response Needed (Yes/No). Sort by position.\"" },
  { title: "The Art of the Follow-Up", subtitle: "Iteration", description: "Your first answer is never the final answer. The magic is in the refinements.", image: "/chapters/ch7-The_Art_of_the_Follow-Up_small.png", chapterId: "ch07",
    lesson: "Your first prompt gets you 70% there. The follow-up gets you to 95%. Treat AI like a conversation, not a vending machine.\n\nPower follow-ups:\n• \"Make it more formal / less formal\"\n• \"Now rewrite this for a non-technical audience\"\n• \"Cut this in half\"\n• \"Add specific numbers and dates where you used vague language\"\n• \"What did you leave out that I should consider?\"\n• \"Challenge your own recommendation — what's the strongest argument against it?\"\n\nCounty example: Start with \"Draft talking points for the County Administrator about the new stormwater fee.\" Then follow up: \"Now add a FAQ section with the 5 questions residents will most likely ask.\" Then: \"Make the tone less bureaucratic — write it like you're explaining to a neighbor.\"\n\nEach follow-up costs you 10 seconds and dramatically improves the output." },
  { title: "Negative Prompting", subtitle: "What NOT to do", description: "Telling AI what NOT to do is just as powerful as telling it what to do. Edit before the AI even begins.", image: "/chapters/ch8-Negative_prompting_small.png", chapterId: "ch26",
    lesson: "Constraints are as powerful as instructions. Tell AI what to avoid and you eliminate entire categories of bad output before they happen.\n\nCommon constraints:\n• \"Do not use jargon or acronyms without defining them\"\n• \"Do not make up statistics or cite sources that may not exist\"\n• \"Do not include a greeting or sign-off\"\n• \"Do not exceed 300 words\"\n• \"Do not use bullet points — use complete paragraphs only\"\n\nCounty example: \"Write a public notice about the water main repair on Cortez Road. Do NOT include: technical engineering terms, estimated costs, contractor names, or any language that could be interpreted as assigning fault. DO include: affected area, timeline, alternative routes, and the 311 number for questions.\"\n\nPro tip: If AI keeps doing something you don't want, add it as an explicit constraint rather than just rephrasing your ask." },
  { title: "Task Chaining", subtitle: "Modular decomposition", description: "Break the big task into smaller tasks. AI solves each sub-task more reliably than the whole.", image: "/chapters/ch09-task_chaining_small.png", chapterId: "ch09",
    lesson: "Big tasks produce messy results. Break them into a chain of smaller tasks and the quality jumps dramatically.\n\nInstead of: \"Write a complete project plan for the new park.\"\nDo this:\n1. \"List the 8 major phases of a municipal park construction project.\"\n2. \"For phase 3 (Design), list the deliverables, estimated timeline, and responsible parties.\"\n3. \"Draft the RFP scope of work for the landscape architecture firm, based on the design phase deliverables above.\"\n\nEach step builds on the previous one. You can review and correct at each stage.\n\nCounty example: Preparing a board presentation?\n1. \"Summarize the key data points from this report.\" (paste report)\n2. \"Organize these into 5 slides with headers.\"\n3. \"Write speaker notes for each slide — 2 minutes per slide.\"\n4. \"Generate 3 likely questions commissioners will ask and draft responses.\"\n\nFour focused prompts beat one giant prompt every time." },
  { title: "The Prompt Recipe Book", subtitle: "High-impact templates", description: "Use these templates to solve 80% of your daily AI tasks. Plug-and-play prompts for writing, analysis, data, and planning.", image: "/chapters/ch-10_Cheatsheet_small.png", chapterId: null,
    lesson: "You don't need to write every prompt from scratch. These templates handle most county work:\n\n• Summarizer: \"Summarize [document] in [format] for [audience]. Keep under [length].\"\n• Rewriter: \"Rewrite this for [audience]. Keep the same facts. Change the tone to [formal/casual/plain].\"\n• Extractor: \"Extract [fields] from the following text. If missing, write 'Not found.' Format as a table.\"\n• Comparer: \"Compare [A] and [B] on these dimensions: [list]. Use a table. Add a recommendation row.\"\n• Drafter: \"Act as [role]. Draft a [document type] about [topic] for [audience]. Include [sections]. Keep under [length].\"\n• Reviewer: \"Review this [document] for [criteria]. List issues as: Location, Issue, Suggested Fix.\"\n\nSee the Recipes tab for ready-to-use templates you can copy or send to the Prompt Builder." },
  { title: "Image Prompting", subtitle: "DALL-E, Midjourney, etc.", description: "Describe visuals like a director, not a poet. Subject, style, composition, details, constraints.", image: "/chapters/ch11-Image_Prompting_small.png", chapterId: "ch28",
    lesson: "Image AI needs you to think like a photographer, not a writer. Describe what you see, not what you feel.\n\nThe formula: Subject + Style + Composition + Details + Constraints\n\nExample: \"A professional photograph of the Manatee County Government Center building, straight-on angle, clear blue sky, well-maintained landscaping in foreground, high resolution, corporate annual report style, no people visible.\"\n\nTips for county use:\n• \"Infographic style\" for presentations\n• \"Clean vector illustration\" for public-facing materials\n• \"Photorealistic\" for mockups\n• Always specify \"no text in the image\" — AI-generated text is usually garbled\n• Describe the mood: \"welcoming,\" \"professional,\" \"approachable\"\n\nNote: Check your county's AI image policy before using AI-generated images in official materials. Some jurisdictions require disclosure." },
  { title: "Testing Your Prompts", subtitle: "Consistency and quality", description: "A prompt is only good if it works every time — not just once. Run it 3 times. If results differ, add constraints.", image: "/chapters/ch12-testing-your-prompt_small.png", chapterId: "ch29",
    lesson: "A prompt that works once might not work next time. AI outputs vary between runs. Before you rely on a prompt for recurring work, test it.\n\nThe 3-run test:\n1. Run the same prompt 3 times\n2. Compare the outputs\n3. If they differ in structure or key content, your prompt needs more constraints\n\nWhat to check:\n• Does the format stay consistent?\n• Are the key facts always included?\n• Does the length stay in range?\n• Does the tone match every time?\n\nFix inconsistency by:\n• Adding explicit format requirements\n• Including examples (few-shot)\n• Adding constraints (\"always include,\" \"never omit\")\n• Being more specific about length and structure\n\nCounty example: If you use a prompt to draft weekly status updates, run it 3 times with the same inputs. If one run uses bullets and another uses paragraphs, add \"Format: exactly 5 bullet points\" to lock it down." },
  { title: "Avoiding Bad Answers", subtitle: "Limitations and defenses", description: "Good prompting is not only about getting great outputs — it's also about preventing bad ones. The Anti-Hallucination Toolkit.", image: "/chapters/ch13-avoiding_bad_answers_small.png", chapterId: "ch30",
    lesson: "AI will confidently make things up. It will cite laws that don't exist, invent statistics, and fabricate names. Your job is to build defenses into your prompts.\n\nAnti-hallucination rules to include:\n• \"Only use information I provide. Do not add outside facts.\"\n• \"If you're unsure about something, say so explicitly.\"\n• \"Do not cite specific statutes, case law, or statistics unless I provide them.\"\n• \"If the answer requires information you don't have, list what you need instead of guessing.\"\n\nHigh-risk areas for county work:\n• Legal references (always verify statutes and ordinances)\n• Budget numbers (AI will estimate if you don't provide actuals)\n• Dates and deadlines (AI fills in plausible but wrong dates)\n• Names and titles (AI invents realistic-sounding staff names)\n\nGolden rule: AI is a drafting tool, not a source of truth. Every fact in AI output that goes into an official document must be verified by a human." },
  { title: "Capstone: Putting It All Together", subtitle: "The Master Blueprint", description: "One final prompt that uses everything you've learned. The master template for any task.", image: "/chapters/ch14-putting_it_all_together_small.png", chapterId: null,
    lesson: "The Master Blueprint combines every technique into one framework. Use this for complex, high-stakes prompts:\n\n1. Role — Who is the AI?\n2. Context — Background and constraints\n3. Task — What needs to be done\n4. Input data — Paste or reference the source material\n5. Output format — Exactly how the result should look\n6. Examples — Show one good output (few-shot)\n7. Chain-of-thought — \"Think step by step\"\n8. Constraints — What NOT to do\n9. Quality check — \"Before finalizing, verify that you have...\"\n\nYou won't need all 9 steps for every prompt. A quick email needs steps 1-3. A board presentation needs all 9.\n\nTry building one in the Prompt Builder — it walks you through each block. Or jump to the Prompt Lab to practice with real county scenarios.\n\nThe best prompt engineers aren't the ones who memorize rules — they're the ones who practice. Start with the templates, iterate, and build your own library of prompts that work for your specific job." },
];

/** Number of Jumpstart course chapters — derived, never hardcoded. */
export const JUMPSTART_CHAPTER_COUNT = jumpstartChapters.length;

// ─── Prompt Recipes ──────────────────────────────────────────────────────────

export interface PromptRecipe {
  category: string;
  icon: string;
  title: string;
  template: string;
}

export const promptRecipes: PromptRecipe[] = [
  // Writing
  { category: "Writing", icon: "✏️", title: "Rewrite for Clarity", template: "Rewrite the text below for clarity and flow. Keep the meaning the same. Avoid jargon, keep sentences short.\n\nText:\n[PASTE HERE]" },
  { category: "Writing", icon: "📋", title: "Summarize with Structure", template: "Summarize the following text in this structure:\n1. One-sentence summary\n2. Three key points\n3. One action item\n\nText:\n[PASTE HERE]" },
  { category: "Writing", icon: "📝", title: "Turn Notes into Prose", template: "Turn these rough bullet points into a professional paragraph. Keep all facts. Smooth out transitions. Match a formal but readable tone.\n\nNotes:\n[PASTE HERE]" },
  { category: "Writing", icon: "🧒", title: "Explain Like I'm 12", template: "Explain this concept to a curious 12-year-old. Use simple words, one analogy, and no jargon.\n\nTopic: [TOPIC]" },
  // Analysis
  { category: "Analysis", icon: "⚖️", title: "Compare Two Options", template: "Compare [A] and [B] on these dimensions:\n- Strengths\n- Weaknesses\n- Use cases\n- Recommendation\n\nBe objective. Use a table format." },
  { category: "Analysis", icon: "🔍", title: "Deep-Dive Reasoning", template: "Analyze this topic step-by-step:\n\n1. Define the core issue\n2. List contributing factors\n3. Evaluate evidence for and against\n4. Provide a reasoned conclusion\n\nTopic: [TOPIC]" },
  { category: "Analysis", icon: "📊", title: "SWOT Analysis", template: "Perform a SWOT analysis for [SUBJECT]:\n\nStrengths:\nWeaknesses:\nOpportunities:\nThreats:\n\nInclude 3-4 items per category with brief explanations." },
  // Data
  { category: "Data", icon: "🏷️", title: "Extract Key Fields", template: "Extract these fields from the text below:\n- Name\n- Role\n- Key Skills\n- Experience Level\n- Contact Info\n\nIf a field is missing, write 'Not found'.\n\nText:\n[PASTE HERE]" },
  { category: "Data", icon: "🧹", title: "Clean and Structure Data", template: "Take this messy data and restructure it into a clean table with columns: [COLUMN1], [COLUMN2], [COLUMN3].\n\nRaw data:\n[PASTE HERE]" },
  // Planning
  { category: "Planning", icon: "📅", title: "Project Plan", template: "Create a project plan for [PROJECT] using this structure:\n- Objective\n- Milestones (with dates)\n- Risks\n- Required resources\n- Success criteria\n\nTimeframe: [DURATION]" },
  { category: "Planning", icon: "🗓️", title: "Meeting Agenda", template: "Create a structured agenda for a [DURATION] meeting about [TOPIC].\n\nInclude:\n- Time allocation per item\n- Discussion lead\n- Expected outcome per item\n- Pre-read materials needed" },
  // County-Specific
  { category: "County Work", icon: "📢", title: "Public Notice", template: "Draft a public notice for Manatee County residents about [TOPIC].\n\nInclude: effective date, what changes, who is affected, what action residents need to take, and contact information.\n\nTone: Clear, professional, accessible at 8th grade reading level." },
  { category: "County Work", icon: "🏛️", title: "Board Memo", template: "Draft a memo to the Board of County Commissioners about [TOPIC].\n\nStructure:\n1. Executive Summary (2-3 sentences)\n2. Background\n3. Analysis\n4. Options\n5. Staff Recommendation\n6. Fiscal Impact\n\nKeep under 2 pages." },
  { category: "County Work", icon: "📁", title: "Records Request Response", template: "Draft a response to public records request #[NUMBER] for [DESCRIPTION].\n\nInclude: acknowledgment, search scope, estimated timeline, any applicable exemptions under Florida Statute 119, and contact information for the records custodian." },
];

/** Number of prompt recipes — derived, never hardcoded. */
export const PROMPT_RECIPE_COUNT = promptRecipes.length;
